GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/id:5... 


###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Bobby Chan",
    "number": "0912390"
}
